### ISSUE TITLE
Heroku app in browser shows error

### ISSUE THREAD

**Issue by vinson-ridenour** [codeship-library/php-laravel-todoapp#6]
Hello,
I was able to follow this tutorial all the way to the end and my codeship project and heroku builds both show successful, however when I open the app in the browser I see: 

"Sorry, the page you are looking for could not be found." 

https://secure-lowlands-55592.herokuapp.com/

Please help!
![screen shot 2018-10-06 at 16 42 00](https://user-images.githubusercontent.com/20788637/46576772-e768b600-c986-11e8-9d76-b49f9b6eb7c2.png)

**Comment by joesiewert** [comment]
@vinson-ridenour sorry we didn't see this sooner. If I remember correctly, this example creates a todo API backend, so you wouldn't see anything directly in the browser, but would rather need to reach the end points directly with something like `curl` or [Postman](https://www.getpostman.com). If you need further assistance, reach out to us at support@codeship.com as well.
